### ISSUE TITLE
Site loads but data does not

### ISSUE THREAD

**Issue by vilhok** [skydivejkl/hyppykeli.fi#11]
I wonder if this has something to do with it:

"Rekisteröityneiden käyttäjien tulee vuoden 2019 loppuun mennessä muuttaa palvelun osoite käyttämään uusia osoitteita. Osoitteet, joissa on Ilmatieteen laitoksen api-avain mukana, eivät toimi enää vuoden 2019 jälkeen." at https://www.ilmatieteenlaitos.fi/avoin-data

**Comment by esamattis** [comment]
Most likely. Will fix before the season.

**Comment by esamattis** [comment]
Fixed by @wexi79!
