### ISSUE TITLE
Weather station at Turku Airport

### ISSUE THREAD

**Issue by vilhok** [skydivejkl/hyppykeli.fi#8]
According to https://ilmatieteenlaitos.fi/havaintoasemat there is a weather station at Turku Airport. Currently Hyppykeli.fi uses data from Artukainen which is 8km from the dropzone. Does the weather station at airport provide the necessary data to be used in hyppykeli.fi?

**Comment by epeli** [comment]
Last time I checked the data just wasn't available in the FMI API for some reason. Need to recheck this since it's been two years or so.

**Comment by vilhok** [comment]
Some skydivers reported this station as "new" as some data was visible online.
![image](https://user-images.githubusercontent.com/15260537/58704456-bc6b2080-83b4-11e9-97c5-9788187a00cf.png)
Though on the list at ilmatieteenlaitos.fi the station has existed since 1955.

**Comment by epeli** [comment]
Woo, the data is now available!
